# Generated by Django 4.2.11 on 2024-12-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('expected_participants', models.IntegerField()),
                ('seats_left', models.IntegerField()),
                ('poster_url', models.URLField(blank=True)),
                ('registration_link', models.URLField(blank=True)),
            ],
        ),
    ]
